"""empty message

Revision ID: 065bde4614b7
Revises: 
Create Date: 2019-03-22 14:23:27.967111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '065bde4614b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notebook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notebook')
    # ### end Alembic commands ###
